// PetroPulse AI — Business Profile Templates
// Used by recommendation and impact engines

export const businessProfiles = [
  {
    id: 'importer',
    label: 'Oil Importer',
    icon: '🛳️',
    color: '#2d5be3',
    description: 'Companies importing crude or refined petroleum products for domestic distribution.',
    monthlyVolumeBbl: 250000,
    monthlyFuelConsumption: 0,
    annualRevenue: 850000000,
    profitMarginPct: 6.5,
    transportDependencyPct: 65,
    supplierDependencyPct: 72,
    hedgingCapabilityPct: 35,
    currencyRisk: 'high',
    primaryConcerns: ['price_lock', 'supply_security', 'forex_risk'],
    kpis: [
      { label: 'Import Volume',        value: '2.5L bbl/mo',  icon: '📦' },
      { label: 'Primary Supplier',     value: 'Saudi Arabia',  icon: '🌍' },
      { label: 'Hedging Coverage',     value: '35%',           icon: '🛡️' },
      { label: 'USD Exposure',         value: '₹21 Cr/mo',     icon: '💱' },
    ],
    defaultInputs: {
      monthlyConsumption: 250000,
      procurementVolume: 250000,
      currentPrice: 82.4,
      priceChangeExpected: 6,
      transportDependency: 65,
      supplierDependency: 72,
    },
  },
  {
    id: 'logistics',
    label: 'Logistics Company',
    icon: '🚚',
    color: '#8b5cf6',
    description: 'Fleet-based logistics and transport companies with high fuel dependency.',
    monthlyVolumeBbl: 0,
    monthlyFuelConsumption: 50000,
    annualRevenue: 120000000,
    profitMarginPct: 18,
    transportDependencyPct: 92,
    supplierDependencyPct: 55,
    hedgingCapabilityPct: 15,
    currencyRisk: 'low',
    primaryConcerns: ['diesel_cost', 'route_optimization', 'fuel_surcharge'],
    kpis: [
      { label: 'Fleet Size',           value: '240 vehicles', icon: '🚛' },
      { label: 'Monthly Diesel',       value: '50,000 L',     icon: '⛽' },
      { label: 'Fuel as % Revenue',    value: '28%',          icon: '📊' },
      { label: 'Client Surcharge Gap', value: '14 days',      icon: '⏱️' },
    ],
    defaultInputs: {
      monthlyConsumption: 50000,
      procurementVolume: 50000,
      currentPrice: 94.5,
      priceChangeExpected: 8,
      transportDependency: 92,
      supplierDependency: 55,
    },
  },
  {
    id: 'fleet',
    label: 'Fleet Operator',
    icon: '🚌',
    color: '#f59e0b',
    description: 'Bus fleets, taxi aggregators, car rental companies, and private vehicle fleets.',
    monthlyVolumeBbl: 0,
    monthlyFuelConsumption: 18000,
    annualRevenue: 45000000,
    profitMarginPct: 22,
    transportDependencyPct: 88,
    supplierDependencyPct: 40,
    hedgingCapabilityPct: 8,
    currencyRisk: 'low',
    primaryConcerns: ['diesel_price', 'route_cost', 'maintenance'],
    kpis: [
      { label: 'Fleet Count',         value: '85 vehicles', icon: '🚘' },
      { label: 'Avg Distance/Day',    value: '12,000 km',   icon: '🛣️' },
      { label: 'Fuel Per Vehicle',    value: '212 L/mo',    icon: '⛽' },
      { label: 'Fuel Cost Share',     value: '34% Opex',    icon: '💰' },
    ],
    defaultInputs: {
      monthlyConsumption: 18000,
      procurementVolume: 18000,
      currentPrice: 94.5,
      priceChangeExpected: 7,
      transportDependency: 88,
      supplierDependency: 40,
    },
  },
  {
    id: 'manufacturer',
    label: 'Manufacturer',
    icon: '🏭',
    color: '#10b981',
    description: 'Industrial manufacturers using petroleum as fuel or feedstock for production.',
    monthlyVolumeBbl: 0,
    monthlyFuelConsumption: 35000,
    annualRevenue: 380000000,
    profitMarginPct: 14,
    transportDependencyPct: 58,
    supplierDependencyPct: 68,
    hedgingCapabilityPct: 22,
    currencyRisk: 'medium',
    primaryConcerns: ['energy_cost', 'feedstock_price', 'production_planning'],
    kpis: [
      { label: 'Energy Spend/Mo',     value: '₹2.1 Cr',       icon: '⚡' },
      { label: 'Oil Dependency',      value: '68%',            icon: '🛢️' },
      { label: 'Margin Sensitivity',  value: '±1.2% per ₹5',  icon: '📉' },
      { label: 'Hedging Ratio',       value: '22%',            icon: '🛡️' },
    ],
    defaultInputs: {
      monthlyConsumption: 35000,
      procurementVolume: 35000,
      currentPrice: 85.0,
      priceChangeExpected: 6,
      transportDependency: 58,
      supplierDependency: 68,
    },
  },
  {
    id: 'sme',
    label: 'SME Buyer',
    icon: '🏪',
    color: '#ef4444',
    description: 'Small and medium enterprises with moderate fuel needs and limited financial buffers.',
    monthlyVolumeBbl: 0,
    monthlyFuelConsumption: 4500,
    annualRevenue: 12000000,
    profitMarginPct: 28,
    transportDependencyPct: 60,
    supplierDependencyPct: 82,
    hedgingCapabilityPct: 3,
    currencyRisk: 'low',
    primaryConcerns: ['monthly_budget', 'price_surprise', 'supplier_reliability'],
    kpis: [
      { label: 'Monthly Fuel Cost',   value: '₹3.8 L',        icon: '💸' },
      { label: 'Single Supplier',     value: '82%',            icon: '⚠️' },
      { label: 'Cash Buffer',         value: '18 days',        icon: '🏦' },
      { label: 'Price Sensitivity',   value: 'Very High',      icon: '📊' },
    ],
    defaultInputs: {
      monthlyConsumption: 4500,
      procurementVolume: 4500,
      currentPrice: 94.5,
      priceChangeExpected: 8,
      transportDependency: 60,
      supplierDependency: 82,
    },
  },
];

export default businessProfiles;
