// PetroPulse AI — 60-Day Price Forecast Data
// Generated by mock prediction engine

function generateForecast() {
  const forecasts = [];
  const today = new Date('2026-04-09');
  let brent = 82.4, wti = 78.1, confidence = 91;

  for (let i = 1; i <= 60; i++) {
    const d = new Date(today);
    d.setDate(d.getDate() + i);

    // Mild upward trend with noise
    brent += (Math.random() - 0.46) * 1.4 + 0.08;
    wti    = brent - (3.5 + Math.random() * 1.5);
    confidence = Math.max(50, confidence - (Math.random() * 0.7));

    const lower = brent - (1.2 + i * 0.06);
    const upper = brent + (1.2 + i * 0.07);

    forecasts.push({
      date:        d.toISOString().split('T')[0],
      day:         i,
      brent:       +brent.toFixed(2),
      wti:         +wti.toFixed(2),
      brentLower:  +lower.toFixed(2),
      brentUpper:  +upper.toFixed(2),
      confidence:  +confidence.toFixed(1),
      signal:      brent > 86 ? 'sell' : brent < 78 ? 'buy' : 'hold',
    });
  }
  return forecasts;
}

export const forecasts = generateForecast();

export const forecastSummary = {
  currentBrent:      82.4,
  priceIn7Days:      84.2,
  priceIn30Days:     86.8,
  priceIn60Days:     88.5,
  trend:             'upward',
  trendStrength:     'moderate',
  confidenceAt7d:    91,
  confidenceAt30d:   76,
  confidenceAt60d:   61,
  keyDrivers: [
    'OPEC+ supply discipline holding',
    'China demand recovery above expectations',
    'USD/INR weakening 1.8% YTD',
    'Geopolitical premium from Red Sea tensions',
  ],
  riskFactors: [
    'US Fed rate decision uncertainty',
    'Russian supply circumvention via India',
    'Potential demand softness from EU recession',
  ],
};

export default forecasts;
