// PetroPulse AI — Geopolitical & Market Scenarios
// Used by scenarioEngine and simulator pages

export const scenarios = [
  {
    id: 'opec_cut',
    title: 'OPEC Production Cut',
    icon: '🛢️',
    category: 'supply',
    severity: 'high',
    color: '#ef4444',
    priceImpactMin: 5,
    priceImpactMax: 11,
    priceDirection: 'up',
    supplyRisk: 82,
    transportRisk: 28,
    demandImpact: -5,
    duration: '3–6 months',
    confidence: 88,
    summary: 'OPEC+ agrees to cut production by 1.5M bbl/day, tightening global supply.',
    explanation: 'A coordinated production cut by major OPEC+ nations reduces global oil availability by approximately 1.5 million barrels per day. Historically, such cuts push Brent crude up 7–12% within 4–6 weeks.',
    businessImpacts: {
      'Oil Importer':      'Higher procurement cost. Lock in contracts at current prices immediately.',
      'Logistics Company': 'Fuel surcharges will rise. Review client contracts for pass-through clauses.',
      'Fleet Operator':    'Diesel costs up 8–12%. Consider bulk buying or hedging now.',
      'Manufacturer':      'Energy costs increase. Assess production schedule to front-load output.',
      'SME Buyer':         'Buy your monthly stock now at current rates before the price spike.',
    },
    recommendedAction: 'Buy or contract at current prices. Consider forward contracts for 60–90 days.',
    geographies: ['Saudi Arabia', 'UAE', 'Iraq', 'Russia', 'Kuwait'],
  },
  {
    id: 'middle_east_conflict',
    title: 'Middle East Supply Disruption',
    icon: '⚠️',
    category: 'geopolitics',
    severity: 'critical',
    color: '#dc2626',
    priceImpactMin: 10,
    priceImpactMax: 22,
    priceDirection: 'up',
    supplyRisk: 94,
    transportRisk: 78,
    demandImpact: -12,
    duration: '1–4 months',
    confidence: 72,
    summary: 'Conflict escalation in the Middle East disrupts Strait of Hormuz passage.',
    explanation: 'The Strait of Hormuz handles ~21% of global oil trade. Any disruption forces rerouting through longer, costlier paths, adding 14–21 days to delivery and $4–8/bbl in transport cost.',
    businessImpacts: {
      'Oil Importer':      'Supply disruption likely. Activate alternative suppliers from West Africa and Norway.',
      'Logistics Company': 'Route insurance premiums surge 300–500%. Plan for extended delivery timelines.',
      'Fleet Operator':    'Severe diesel shortage risk. Ensure 45-day strategic reserve if possible.',
      'Manufacturer':      'Production at risk. Identify alternative energy sources and reduce waste.',
      'SME Buyer':         'Prices spike fast. Buy as much as budget allows in the next 48 hours.',
    },
    recommendedAction: 'Diversify supplier mix immediately. Seek West African and European alternatives.',
    geographies: ['Iran', 'Iraq', 'Saudi Arabia', 'Bahrain', 'Yemen'],
  },
  {
    id: 'sanctions',
    title: 'Sanctions on Major Exporter',
    icon: '🚫',
    category: 'geopolitics',
    severity: 'high',
    color: '#f97316',
    priceImpactMin: 4,
    priceImpactMax: 9,
    priceDirection: 'up',
    supplyRisk: 71,
    transportRisk: 45,
    demandImpact: -8,
    duration: '6–18 months',
    confidence: 81,
    summary: 'International sanctions imposed on a top-5 oil exporter reduce global supply.',
    explanation: 'Sanctions effectively remove 1–3Mbbl/day from the global market. While some supply is rerouted through third countries, net availability drops, sustaining elevated prices.',
    businessImpacts: {
      'Oil Importer':      'Sanctioned country supply must stop. Reallocate contracts to alternatives.',
      'Logistics Company': 'Shipping insurance for routes near sanctioned nation rises significantly.',
      'Fleet Operator':    'Moderate price increase. Optimize routes and reduce unnecessary trips.',
      'Manufacturer':      'Input cost rises. Review quarterly budget and identify savings elsewhere.',
      'SME Buyer':         'Price rise is manageable. Negotiate with your supplier for a longer price lock.',
    },
    recommendedAction: 'Shift 20–30% of procurement to non-sanctioned suppliers within 30 days.',
    geographies: ['Russia', 'Venezuela', 'Iran', 'Libya'],
  },
  {
    id: 'shipping_blockage',
    title: 'Shipping Route Blockage',
    icon: '🚢',
    category: 'logistics',
    severity: 'high',
    color: '#8b5cf6',
    priceImpactMin: 3,
    priceImpactMax: 7,
    priceDirection: 'up',
    supplyRisk: 55,
    transportRisk: 91,
    demandImpact: -6,
    duration: '2–8 weeks',
    confidence: 85,
    summary: 'Key shipping lane blocked due to geopolitical tensions or accident.',
    explanation: 'Blockage of major routes like Suez Canal or Malacca Strait forces tankers to add 7–21 days to voyages. This effectively reduces available tanker capacity by 8–15% globally.',
    businessImpacts: {
      'Oil Importer':      'Expect 15–25 day delivery delays. Maintain higher inventory buffer.',
      'Logistics Company': 'Route delays cascade across your client deliveries. Plan proactively.',
      'Fleet Operator':    'Fuel costs stable but diesel availability may tighten regionally.',
      'Manufacturer':      'Raw material delivery delays possible. Stock up on energy inputs.',
      'SME Buyer':         'Your local pumps may see supply tightness in 2–3 weeks.',
    },
    recommendedAction: 'Increase inventory levels. Explore alternative supplier locations closer to market.',
    geographies: ['Suez Canal', 'Strait of Hormuz', 'Malacca Strait', 'Red Sea'],
  },
  {
    id: 'demand_surge_asia',
    title: 'Demand Surge in Asia',
    icon: '📈',
    category: 'demand',
    severity: 'moderate',
    color: '#eab308',
    priceImpactMin: 3,
    priceImpactMax: 8,
    priceDirection: 'up',
    supplyRisk: 40,
    transportRisk: 35,
    demandImpact: 18,
    duration: '1–3 months',
    confidence: 79,
    summary: 'Rapid economic recovery in China and India spikes crude demand unexpectedly.',
    explanation: 'China and India together account for ~25% of global oil demand. A simultaneous demand surge tightens the global supply-demand balance, pushing prices up within weeks.',
    businessImpacts: {
      'Oil Importer':      'Competition for cargoes intensifies. Lock in volumes for Q3 now.',
      'Logistics Company': 'Tanker freight rates rise. Review your freight cost model for clients.',
      'Fleet Operator':    'Diesel demand driven: expect moderate cost increases over 6–8 weeks.',
      'Manufacturer':      'Petrochemical feedstock costs could rise. Review production planning.',
      'SME Buyer':         'Gradual price increase expected. Monthly purchases should be brought forward.',
    },
    recommendedAction: 'Accelerate procurement. Lock in freight and supply contracts for next 60 days.',
    geographies: ['China', 'India', 'Vietnam', 'Indonesia'],
  },
  {
    id: 'rupee_depreciation',
    title: 'Rupee Depreciation vs USD',
    icon: '₹',
    category: 'currency',
    severity: 'moderate',
    color: '#06b6d4',
    priceImpactMin: 2,
    priceImpactMax: 5,
    priceDirection: 'up',
    supplyRisk: 20,
    transportRisk: 15,
    demandImpact: -8,
    duration: '1–6 months',
    confidence: 86,
    summary: 'INR depreciates by 5–8% against USD, making oil imports significantly costlier.',
    explanation: 'India imports ~85% of its crude oil. A 5% INR depreciation raises import costs by approximately ₹4,200–5,100 per metric ton, directly impacting end-user prices.',
    businessImpacts: {
      'Oil Importer':      'Your import bill rises 5–8% immediately. Hedge USD exposure if possible.',
      'Logistics Company': 'Fuel costs in INR rise even without global price movement. Raise surcharges.',
      'Fleet Operator':    'Diesel prices will rise at pumps. Review monthly fuel budget upward.',
      'Manufacturer':      'All energy costs in INR rise. Pass through selectively to product pricing.',
      'SME Buyer':         'Petrol and diesel retail prices may rise ₹3–6/liter. Budget accordingly.',
    },
    recommendedAction: 'Forward hedge USD exposure for 30–60 days. Buy INR-denominated inventory now.',
    geographies: ['India', 'Bangladesh', 'Pakistan', 'Sri Lanka'],
  },
  {
    id: 'refinery_outage',
    title: 'Major Refinery Outage',
    icon: '🏭',
    category: 'supply',
    severity: 'high',
    color: '#ef4444',
    priceImpactMin: 4,
    priceImpactMax: 10,
    priceDirection: 'up',
    supplyRisk: 68,
    transportRisk: 30,
    demandImpact: -10,
    duration: '3–10 weeks',
    confidence: 82,
    summary: 'Unexpected shutdown of a major refinery tightens refined product supply.',
    explanation: 'A large refinery outage (200,000+ bbl/day capacity) reduces regional product supply of diesel, gasoline, and jet fuel, pushing refined product premiums higher.',
    businessImpacts: {
      'Oil Importer':      'Crude demand relatively unaffected. But refined product imports may rise.',
      'Logistics Company': 'Diesel prices spike sharply in affected region. Source from alternate regions.',
      'Fleet Operator':    'Fuel station rationing possible in affected zone. Fill up tanks proactively.',
      'Manufacturer':      'Fuel oil and naphtha prices rise. Consider production optimizations.',
      'SME Buyer':         'Diesel and petrol prices will increase at pumps within 1–2 weeks.',
    },
    recommendedAction: 'Build a 30-day diesel reserve. Identify alternative fuel suppliers in your zone.',
    geographies: ['India', 'Middle East', 'Singapore', 'US Gulf Coast'],
  },
  {
    id: 'port_congestion',
    title: 'Port Congestion Delay',
    icon: '⚓',
    category: 'logistics',
    severity: 'moderate',
    color: '#64748b',
    priceImpactMin: 1,
    priceImpactMax: 4,
    priceDirection: 'up',
    supplyRisk: 38,
    transportRisk: 82,
    demandImpact: -4,
    duration: '2–6 weeks',
    confidence: 78,
    summary: 'Major ports face backlogs, causing 10–21 day delays in cargo discharge.',
    explanation: 'Port congestion slows the release of oil into circulation, creating temporary regional shortages. Tanker charter rates rise as vessels are stuck at anchor waiting for berths.',
    businessImpacts: {
      'Oil Importer':      'Expect delayed deliveries. Communicate with downstream customers proactively.',
      'Logistics Company': 'Your terminal operations face queue delays. Adjust schedules accordingly.',
      'Fleet Operator':    'Minimal direct impact on fuel prices but allow 1–2 week buffer on imports.',
      'Manufacturer':      'Watch feedstock arrival schedules closely. Keep 2-week extra inventory.',
      'SME Buyer':         'Local supply unaffected. Prices stable. No urgent action needed.',
    },
    recommendedAction: 'Maintain buffer inventory. Communicate delays to your supply chain partners.',
    geographies: ['Colombo', 'Singapore', 'Rotterdam', 'Mumbai', 'Jebel Ali'],
  },
  {
    id: 'price_crash',
    title: 'Global Demand Collapse',
    icon: '📉',
    category: 'demand',
    severity: 'high',
    color: '#10b981',
    priceImpactMin: -15,
    priceImpactMax: -8,
    priceDirection: 'down',
    supplyRisk: 25,
    transportRisk: 20,
    demandImpact: -30,
    duration: '3–12 months',
    confidence: 68,
    summary: 'Global recession fears cause oil demand to collapse, prices fall sharply.',
    explanation: 'A global economic slowdown reduces oil demand by 3–5 Mbbl/day. Combined with elevated supply, prices crater. Airlines, shipping, and heavy industry cut fuel demand significantly.',
    businessImpacts: {
      'Oil Importer':      'Great time to buy at lower prices. Maximize stock and delay forward contracts.',
      'Logistics Company': 'Fuel costs drop. This is an opportunity to lock in lower prices for 12 months.',
      'Fleet Operator':    'Golden opportunity. Reduce variable costs. Your margins improve temporarily.',
      'Manufacturer':      'Energy cost windfall. Lock in long-term energy supply contracts now.',
      'SME Buyer':         'Prices at bargain levels. Maximize bulk purchases and storage now.',
    },
    recommendedAction: 'This is a buying opportunity. Maximize procurement and secure long-term contracts.',
    geographies: ['Global', 'Europe', 'USA', 'China'],
  },
  {
    id: 'normal_market',
    title: 'Stable Market Conditions',
    icon: '✅',
    category: 'neutral',
    severity: 'low',
    color: '#10b981',
    priceImpactMin: -1,
    priceImpactMax: 2,
    priceDirection: 'sideways',
    supplyRisk: 22,
    transportRisk: 18,
    demandImpact: 0,
    duration: 'Ongoing',
    confidence: 91,
    summary: 'Markets stable with balanced supply and demand. Normal procurement conditions.',
    explanation: 'Supply and demand in equilibrium. Prices likely to remain range-bound in the near term. Standard procurement strategy applies with no urgent action needed.',
    businessImpacts: {
      'Oil Importer':      'Regular procurement schedule. Optimize for cost efficiency and supplier terms.',
      'Logistics Company': 'Stable fuel costs. Focus on route optimization and operational efficiency.',
      'Fleet Operator':    'Predictable costs. Good time to review fuel card contracts and vendor terms.',
      'Manufacturer':      'Stable energy costs. Focus on process optimization and long-term planning.',
      'SME Buyer':         'No urgent action. Maintain your regular buying schedule.',
    },
    recommendedAction: 'Maintain regular procurement. Use this stability to negotiate better supplier terms.',
    geographies: ['Global'],
  },
];

export default scenarios;
