// PetroPulse AI — Shipping Risks & Route Data

export const shippingRisks = [
  {
    id: 'strait_hormuz',
    route: 'Strait of Hormuz',
    from: 'Middle East Gulf',
    to: 'Indian Ocean',
    type: 'strait',
    oilFlowMbbl: 21,
    riskScore: 74,
    status: 'elevated',
    avgDelay: 0,
    delayRisk: 68,
    insurancePremiumMultiplier: 2.8,
    alternativeRoute: 'Saudi Arabia East–West Pipeline / Cape of Good Hope',
    alternativeAddedDays: 14,
    notes: 'Controls ~21% of global oil trade. Any disruption has immediate global price impact.',
    recentIncidents: [
      { date: '2024-01-08', type: 'Houthi missile threat', impact: 'moderate' },
      { date: '2024-04-14', type: 'Iran tanker seizure', impact: 'high' },
    ],
  },
  {
    id: 'suez_canal',
    route: 'Suez Canal',
    from: 'Red Sea',
    to: 'Mediterranean',
    type: 'canal',
    oilFlowMbbl: 9.5,
    riskScore: 61,
    status: 'moderate',
    avgDelay: 3,
    delayRisk: 52,
    insurancePremiumMultiplier: 1.9,
    alternativeRoute: 'Cape of Good Hope',
    alternativeAddedDays: 11,
    notes: 'Key chokepoint between Asia/Middle East and Europe. Always subject to congestion risk.',
    recentIncidents: [
      { date: '2021-03-23', type: 'Ever Given grounding', impact: 'critical' },
      { date: '2024-02-01', type: 'Houthi Red Sea attacks', impact: 'high' },
    ],
  },
  {
    id: 'malacca_strait',
    route: 'Strait of Malacca',
    from: 'Indian Ocean',
    to: 'South China Sea',
    type: 'strait',
    oilFlowMbbl: 16,
    riskScore: 38,
    status: 'stable',
    avgDelay: 0,
    delayRisk: 28,
    insurancePremiumMultiplier: 1.2,
    alternativeRoute: 'Lombok / Sunda Strait',
    alternativeAddedDays: 4,
    notes: 'World\'s busiest shipping lane. Piracy risk exists but maritime patrols are effective.',
    recentIncidents: [
      { date: '2023-07-15', type: 'Piracy attempt', impact: 'minor' },
    ],
  },
  {
    id: 'cape_good_hope',
    route: 'Cape of Good Hope',
    from: 'Atlantic Ocean',
    to: 'Indian Ocean',
    type: 'open_sea',
    oilFlowMbbl: 5.8,
    riskScore: 22,
    status: 'stable',
    avgDelay: 0,
    delayRisk: 15,
    insurancePremiumMultiplier: 1.1,
    alternativeRoute: 'None (this IS the alternative)',
    alternativeAddedDays: 0,
    notes: 'Alternative to Suez Canal when Red Sea risk is high. Adds 10–14 days vs Suez route.',
    recentIncidents: [],
  },
  {
    id: 'bab_el_mandab',
    route: 'Bab-el-Mandab',
    from: 'Red Sea',
    to: 'Gulf of Aden',
    type: 'strait',
    oilFlowMbbl: 8.8,
    riskScore: 82,
    status: 'high-risk',
    avgDelay: 7,
    delayRisk: 78,
    insurancePremiumMultiplier: 4.2,
    alternativeRoute: 'Cape of Good Hope',
    alternativeAddedDays: 12,
    notes: 'Currently under threat from Houthi drone and missile attacks targeting commercial vessels.',
    recentIncidents: [
      { date: '2023-11-19', type: 'Container ship attack', impact: 'high' },
      { date: '2024-01-15', type: 'Multiple tanker attacks', impact: 'critical' },
    ],
  },
  {
    id: 'turkish_straits',
    route: 'Turkish Straits (Bosphorus)',
    from: 'Black Sea',
    to: 'Mediterranean',
    type: 'strait',
    oilFlowMbbl: 3.2,
    riskScore: 45,
    status: 'moderate',
    avgDelay: 2,
    delayRisk: 40,
    insurancePremiumMultiplier: 1.6,
    alternativeRoute: 'Trans-Anatolian Pipeline (TANAP)',
    alternativeAddedDays: 0,
    notes: 'Bottleneck for Russian and Caspian oil exports to European markets.',
    recentIncidents: [
      { date: '2022-12-01', type: 'Turkey insurance dispute', impact: 'moderate' },
    ],
  },
  {
    id: 'denmark_straits',
    route: 'Danish Straits (Øresund)',
    from: 'Baltic Sea',
    to: 'North Sea',
    type: 'strait',
    oilFlowMbbl: 1.8,
    riskScore: 18,
    status: 'stable',
    avgDelay: 0,
    delayRisk: 12,
    insurancePremiumMultiplier: 1.05,
    alternativeRoute: 'Kiel Canal',
    alternativeAddedDays: 0.5,
    notes: 'Critical for North Sea energy exports. Generally low risk.',
    recentIncidents: [],
  },
  {
    id: 'panama_canal',
    route: 'Panama Canal',
    from: 'Atlantic',
    to: 'Pacific',
    type: 'canal',
    oilFlowMbbl: 0.8,
    riskScore: 35,
    status: 'moderate',
    avgDelay: 4,
    delayRisk: 45,
    insurancePremiumMultiplier: 1.3,
    alternativeRoute: 'Cape Horn',
    alternativeAddedDays: 20,
    notes: 'Drought conditions reducing water levels. Vessel size restrictions currently in effect.',
    recentIncidents: [
      { date: '2023-11-01', type: 'Drought water restrictions', impact: 'moderate' },
    ],
  },
  {
    id: 'india_west_coast',
    route: 'India West Coast Ports',
    from: 'Arabian Sea',
    to: 'Indian Refineries',
    type: 'terminal',
    oilFlowMbbl: 4.2,
    riskScore: 25,
    status: 'stable',
    avgDelay: 1,
    delayRisk: 20,
    insurancePremiumMultiplier: 1.1,
    alternativeRoute: 'East Coast Ports (via Sri Lanka)',
    alternativeAddedDays: 3,
    notes: 'Mumbai, JNPT, Kandla handling bulk of India crude imports. Monsoon causes seasonal delays.',
    recentIncidents: [
      { date: '2023-07-20', type: 'Monsoon port congestion', impact: 'minor' },
    ],
  },
  {
    id: 'persian_gulf_terminals',
    route: 'Persian Gulf Loading Terminals',
    from: 'Oil Fields',
    to: 'Export Terminals',
    type: 'terminal',
    oilFlowMbbl: 18,
    riskScore: 55,
    status: 'moderate',
    avgDelay: 1,
    delayRisk: 48,
    insurancePremiumMultiplier: 1.8,
    alternativeRoute: 'Pipeline (IPSA / East-West)',
    alternativeAddedDays: 0,
    notes: 'Multiple export terminals across UAE, Kuwait, Saudi Arabia, Iraq, Qatar.',
    recentIncidents: [
      { date: '2019-09-14', type: 'Abqaiq attack', impact: 'critical' },
      { date: '2024-03-22', type: 'Drone strike near Abu Dhabi', impact: 'low' },
    ],
  },
];

export const shippingRiskSummary = {
  totalOilAtRisk: 21.0, // Mbbl/day at Hormuz
  globalTradeViaRiskyRoutes: 0.38,
  avgInsurancePremiumIncrease: 2.1,
  mostCriticalRoute: 'Bab-el-Mandab',
  currentAlertsCount: 3,
};

export default shippingRisks;
