// PetroPulse AI — Supplier Database
// 28 oil-producing nations and major suppliers with risk profiles

export const suppliers = [
  { id: 'sa',  name: 'Saudi Arabia',   region: 'Middle East',  riskScore: 45, reliability: 94, capacityMbbl: 12.0, shareOfIndiaImport: 18, priceBasis: 'Arab Light OSP', sanctions: false, opecMember: true,  currentStatus: 'stable',    lat: 23.8, lng: 45.1 },
  { id: 'iq',  name: 'Iraq',           region: 'Middle East',  riskScore: 62, reliability: 79, capacityMbbl:  4.5, shareOfIndiaImport: 22, priceBasis: 'Basra Light OSP', sanctions: false, opecMember: true,  currentStatus: 'moderate',  lat: 33.2, lng: 43.7 },
  { id: 'ru',  name: 'Russia',         region: 'Europe/Asia',  riskScore: 78, reliability: 72, capacityMbbl: 11.0, shareOfIndiaImport: 28, priceBasis: 'Urals Spot',     sanctions: true,  opecMember: false, currentStatus: 'elevated',  lat: 61.5, lng: 105.3 },
  { id: 'ae',  name: 'UAE',            region: 'Middle East',  riskScore: 38, reliability: 96, capacityMbbl:  3.4, shareOfIndiaImport:  9, priceBasis: 'Murban OSP',     sanctions: false, opecMember: true,  currentStatus: 'stable',    lat: 23.4, lng: 53.8 },
  { id: 'us',  name: 'United States',  region: 'Americas',     riskScore: 12, reliability: 98, capacityMbbl: 13.2, shareOfIndiaImport:  8, priceBasis: 'WTI Spot',       sanctions: false, opecMember: false, currentStatus: 'stable',    lat: 37.1, lng:-95.7 },
  { id: 'kw',  name: 'Kuwait',         region: 'Middle East',  riskScore: 41, reliability: 92, capacityMbbl:  2.8, shareOfIndiaImport:  6, priceBasis: 'Kuwait Export',  sanctions: false, opecMember: true,  currentStatus: 'stable',    lat: 29.3, lng: 47.5 },
  { id: 'ng',  name: 'Nigeria',        region: 'Africa',       riskScore: 66, reliability: 74, capacityMbbl:  1.7, shareOfIndiaImport:  3, priceBasis: 'Bonny Light',    sanctions: false, opecMember: true,  currentStatus: 'moderate',  lat:  9.1, lng:  8.7 },
  { id: 'ly',  name: 'Libya',          region: 'Africa',       riskScore: 84, reliability: 55, capacityMbbl:  1.2, shareOfIndiaImport:  2, priceBasis: 'ES Sider',       sanctions: false, opecMember: true,  currentStatus: 'high-risk', lat: 26.3, lng: 17.2 },
  { id: 'no',  name: 'Norway',         region: 'Europe',       riskScore: 10, reliability: 99, capacityMbbl:  1.8, shareOfIndiaImport:  1, priceBasis: 'Dated Brent',    sanctions: false, opecMember: false, currentStatus: 'stable',    lat: 64.5, lng: 17.9 },
  { id: 'br',  name: 'Brazil',         region: 'Americas',     riskScore: 28, reliability: 88, capacityMbbl:  3.6, shareOfIndiaImport:  2, priceBasis: 'Tupi OSP',       sanctions: false, opecMember: false, currentStatus: 'stable',    lat:-14.2, lng:-51.9 },
  { id: 'ca',  name: 'Canada',         region: 'Americas',     riskScore: 11, reliability: 97, capacityMbbl:  5.7, shareOfIndiaImport:  1, priceBasis: 'WCS Diff',       sanctions: false, opecMember: false, currentStatus: 'stable',    lat: 56.1, lng:-106.3 },
  { id: 'gh',  name: 'Ghana',          region: 'Africa',       riskScore: 35, reliability: 85, capacityMbbl:  0.18,shareOfIndiaImport:  0.5,priceBasis:'TEN Blend',      sanctions: false, opecMember: false, currentStatus: 'stable',    lat:  7.9, lng:  -1.0 },
  { id: 'vz',  name: 'Venezuela',      region: 'Americas',     riskScore: 92, reliability: 41, capacityMbbl:  0.75,shareOfIndiaImport:  0, priceBasis: 'Merey Spot',     sanctions: true,  opecMember: true,  currentStatus: 'critical',  lat:  6.4, lng:-66.6 },
  { id: 'ir',  name: 'Iran',           region: 'Middle East',  riskScore: 95, reliability: 30, capacityMbbl:  3.5, shareOfIndiaImport:  0, priceBasis: 'Iranian Light',  sanctions: true,  opecMember: true,  currentStatus: 'critical',  lat: 32.4, lng: 53.7 },
  { id: 'az',  name: 'Azerbaijan',     region: 'Central Asia', riskScore: 48, reliability: 82, capacityMbbl:  0.65,shareOfIndiaImport:  0.5,priceBasis:'Azeri Light',     sanctions: false, opecMember: false, currentStatus: 'stable',    lat: 40.1, lng: 47.6 },
  { id: 'kz',  name: 'Kazakhstan',     region: 'Central Asia', riskScore: 52, reliability: 80, capacityMbbl:  1.8, shareOfIndiaImport:  1, priceBasis: 'CPC Blend',      sanctions: false, opecMember: false, currentStatus: 'moderate',  lat: 48.0, lng: 66.9 },
  { id: 'mx',  name: 'Mexico',         region: 'Americas',     riskScore: 38, reliability: 84, capacityMbbl:  1.65,shareOfIndiaImport:  0.5,priceBasis:'Maya Crude',      sanctions: false, opecMember: false, currentStatus: 'stable',    lat: 23.6, lng:-102.5 },
  { id: 'dz',  name: 'Algeria',        region: 'Africa',       riskScore: 44, reliability: 81, capacityMbbl:  1.1, shareOfIndiaImport:  0.5,priceBasis:'Saharan Blend',   sanctions: false, opecMember: true,  currentStatus: 'stable',    lat: 28.0, lng:  2.6 },
  { id: 'qa',  name: 'Qatar',          region: 'Middle East',  riskScore: 32, reliability: 93, capacityMbbl:  2.0, shareOfIndiaImport:  3, priceBasis: 'Qatar Marine',   sanctions: false, opecMember: true,  currentStatus: 'stable',    lat: 25.4, lng: 51.2 },
  { id: 'co',  name: 'Colombia',       region: 'Americas',     riskScore: 42, reliability: 83, capacityMbbl:  0.78,shareOfIndiaImport:  0.5,priceBasis:'Vasconia Crude',  sanctions: false, opecMember: false, currentStatus: 'stable',    lat:  4.6, lng:-74.1 },
  { id: 'ec',  name: 'Ecuador',        region: 'Americas',     riskScore: 46, reliability: 80, capacityMbbl:  0.48,shareOfIndiaImport:  0.2,priceBasis:'Oriente Crude',   sanctions: false, opecMember: false, currentStatus: 'stable',    lat: -1.8, lng:-78.2 },
  { id: 'ao',  name: 'Angola',         region: 'Africa',       riskScore: 55, reliability: 75, capacityMbbl:  1.15,shareOfIndiaImport:  1.5,priceBasis:'Girassol Crude',  sanctions: false, opecMember: true,  currentStatus: 'moderate',  lat:-11.2, lng: 17.9 },
  { id: 'gb',  name: 'UK North Sea',   region: 'Europe',       riskScore: 15, reliability: 96, capacityMbbl:  0.8, shareOfIndiaImport:  0.5,priceBasis:'Forties Blend',   sanctions: false, opecMember: false, currentStatus: 'stable',    lat: 57.0, lng:  1.0 },
  { id: 'om',  name: 'Oman',           region: 'Middle East',  riskScore: 36, reliability: 91, capacityMbbl:  1.0, shareOfIndiaImport:  4, priceBasis: 'Oman OSP',       sanctions: false, opecMember: false, currentStatus: 'stable',    lat: 21.5, lng: 55.9 },
  { id: 'ye',  name: 'Yemen',          region: 'Middle East',  riskScore: 97, reliability: 12, capacityMbbl:  0.05,shareOfIndiaImport:  0, priceBasis: 'Marib Light',    sanctions: false, opecMember: false, currentStatus: 'critical',  lat: 15.6, lng: 48.5 },
  { id: 'sd',  name: 'South Sudan',    region: 'Africa',       riskScore: 88, reliability: 48, capacityMbbl:  0.17,shareOfIndiaImport:  0.2,priceBasis:'Nile Blend',      sanctions: false, opecMember: false, currentStatus: 'high-risk', lat:  6.9, lng: 31.3 },
  { id: 'my',  name: 'Malaysia',       region: 'Asia Pacific', riskScore: 25, reliability: 92, capacityMbbl:  0.56,shareOfIndiaImport:  0.8,priceBasis:'Tapis Crude',     sanctions: false, opecMember: false, currentStatus: 'stable',    lat:  4.2, lng: 108.0 },
  { id: 'tt',  name: 'Trinidad',       region: 'Americas',     riskScore: 30, reliability: 87, capacityMbbl:  0.06,shareOfIndiaImport:  0.1,priceBasis:'Tia Juana Light', sanctions: false, opecMember: false, currentStatus: 'stable',    lat: 10.7, lng:-61.2 },
];

export default suppliers;
